# Generated by Django 5.2.4 on 2025-07-25 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='roblox_avatar_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на аватар Roblox'),
        ),
    ]
