# Generated by Django 5.2.4 on 2025-07-25 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_customuser_roblox_avatar_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='roblox_avatar_url',
            new_name='avatar_url',
        ),
    ]
