# Generated by Django 5.2.4 on 2025-07-25 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_customuser_options_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='roblox_nick',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
