# Generated by Django 5.2.4 on 2025-07-25 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_customuser_roblox_nick'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='roblox_nick',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
