# Generated by Django 5.2.4 on 2025-07-29 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='gamepass_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
