# Generated by Django 5.2.4 on 2025-07-30 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_purchase_gamepass_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bonus_balance',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='promo_code',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='promo_code_used',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
