# Generated by Django 5.2.4 on 2025-07-31 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_customuser_bonus_balance_customuser_promo_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='gamepass_url',
        ),
        migrations.AddField(
            model_name='customuser',
            name='roblox_user_id',
            field=models.BigIntegerField(default=123, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase',
            name='gamepass_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='avatar_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='promo_code',
            field=models.CharField(blank=True, default=123, max_length=6, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='roblox_nick',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
