# Generated by Django 5.2.4 on 2025-08-01 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_customuser_username_alter_customuser_roblox_nick_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='promo_code',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
    ]
