# Generated by Django 5.2.4 on 2025-08-01 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_customuser_promo_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='place_id',
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='gamepass_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='roblox_nick',
            field=models.CharField(default=123, max_length=150, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='roblox_user_id',
            field=models.BigIntegerField(default=12, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='amount',
            field=models.FloatField(default=0.0),
        ),
    ]
