# Generated by Django 5.2.4 on 2025-08-01 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_customuser_username_remove_purchase_place_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='place_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
