# Generated by Django 5.2.4 on 2025-08-01 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
