# Generated by Django 5.2.4 on 2025-08-01 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_delete_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='crypto_address',
            field=models.CharField(blank=True, max_length=42, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='crypto_amount',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='tx_hash',
            field=models.CharField(blank=True, max_length=66, null=True),
        ),
    ]
