# Generated by Django 5.2.4 on 2025-08-01 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_purchase_crypto_address_purchase_crypto_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='crypto_address',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='crypto_amount',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='place_id',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='tx_hash',
        ),
        migrations.AlterField(
            model_name='purchase',
            name='price',
            field=models.FloatField(),
        ),
    ]
