# Generated by Django 5.2.4 on 2025-08-01 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_purchase_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='place_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
