# Generated by Django 5.2.4 on 2025-08-02 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_purchase_place_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='discord_joined',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='telegram_joined',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='vk_subscribed',
            field=models.BooleanField(default=False),
        ),
    ]
