# Generated by Django 5.2.4 on 2025-08-02 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_customuser_discord_joined_customuser_telegram_joined_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='gamepass_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('pending', 'В ожидании'), ('completed', 'Получено'), ('declined', 'Отклонено')], default='pending', max_length=20),
        ),
    ]
