# Generated by Django 5.2.4 on 2025-08-02 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_purchase_gamepass_price_alter_purchase_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='discord_bonus_claimed',
            field=models.BooleanField(default=False, verbose_name='Бонус за Discord получен'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='telegram_bonus_claimed',
            field=models.BooleanField(default=False, verbose_name='Бонус за Telegram получен'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='vk_bonus_claimed',
            field=models.BooleanField(default=False, verbose_name='Бонус за VK получен'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='bonus_balance',
            field=models.IntegerField(default=0, verbose_name='Бонусный баланс'),
        ),
    ]
