# Generated by Django 5.2.4 on 2025-08-02 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_customuser_discord_bonus_claimed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='discord_bonus_claimed',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='telegram_bonus_claimed',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='vk_bonus_claimed',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='discord_joined',
            field=models.BooleanField(default=False, verbose_name='Вступил в Discord'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='telegram_joined',
            field=models.BooleanField(default=False, verbose_name='Вступил в Telegram'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='vk_subscribed',
            field=models.BooleanField(default=False, verbose_name='Подписан на VK'),
        ),
    ]
