# Generated by Django 5.2.4 on 2025-08-02 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_purchase_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='currency',
            field=models.CharField(default='RUB', max_length=3),
        ),
    ]
