# Generated by Django 5.2.4 on 2025-08-04 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_promocode_promocodeactivation'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='active_promo_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activated_by_users', to='core.promocode'),
        ),
    ]
